Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas-datareader in c:\users\hp\appdata\roaming\python\python39\site-packages (0.10.0)
Requirement already satisfied: lxml in c:\users\hp\appdata\roaming\python\python39\site-packages (from pandas-datareader) (4.6.3)
Requirement already satisfied: pandas>=0.23 in c:\users\hp\appdata\roaming\python\python39\site-packages (from pandas-datareader) (1.2.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\hp\appdata\roaming\python\python39\site-packages (from pandas-datareader) (2.25.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\hp\appdata\roaming\python\python39\site-packages (from pandas>=0.23->pandas-datareader) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hp\appdata\roaming\python\python39\site-packages (from pandas>=0.23->pandas-datareader) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\hp\appdata\roaming\python\python39\site-packages (from pandas>=0.23->pandas-datareader) (1.19.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\hp\appdata\roaming\python\python39\site-packages (from requests>=2.19.0->pandas-datareader) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hp\appdata\roaming\python\python39\site-packages (from requests>=2.19.0->pandas-datareader) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\roaming\python\python39\site-packages (from requests>=2.19.0->pandas-datareader) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\hp\appdata\roaming\python\python39\site-packages (from requests>=2.19.0->pandas-datareader) (2.10)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
